/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.2.1/userguide/building_swift_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    val pluginVersionFoojayResolverConvention: String by settings
    val pluginVersionSonarQube: String by settings
    val pluginVersionSpotbugs: String by settings
    // Include 'plugins build' to define convention plugins.
    plugins {
        id("org.gradle.toolchains.foojay-resolver-convention") version pluginVersionFoojayResolverConvention
        id("org.sonarqube") version pluginVersionSonarQube
        id("com.github.spotbugs") version pluginVersionSpotbugs
    }
    includeBuild("build-logic")
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention")
}

rootProject.name = "gradle-java-sample"
include("app", "list", "utilities")
