/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
  `kotlin-dsl`
}

repositories {
  // Use the plugin portal to apply community plugins in convention plugins.
  gradlePluginPortal()
}

dependencies {
  implementation(libs.benManesVersions.gradlePlugin)
  implementation(libs.cucumberCompanion.gradlePlugin)
  implementation(libs.cyclonedx.gradlePlugin)
  implementation(libs.dependencyCheck.gradlePlugin)
  implementation(libs.dependencyTrackCompanion.gradlePlugin)
  implementation(libs.errorprone.gradlePlugin)
  implementation(libs.licenseCheck.gradlePlugin)
  implementation(libs.postgresql.jdbc)
  implementation(libs.sonar.gradlePlugin)
  implementation(libs.spotbugs.gradlePlugin)
}
