/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

val versionCatalog = extensions.getByType<VersionCatalogsExtension>().named("libs")

plugins {
    // Apply the java Plugin to add support for Java.
    java
    id("errorprone")
    id("checkstyle-conventions")
    id("pmd-conventions")
    id("spotbugs-conventions")
    id("dependency-check-conventions")
    id("sonar-project-conventions")
    id("unit-test-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        versionCatalog.findLibrary("apache-commonsText").ifPresent() {
          implementation(it)
        }
    }
}
