/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("gradle.java.sample.java-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("gradle.java.sample.java-cyclonedx-library-conventions")
    id("gradle.java.sample.java-dependency-track-conventions")
}
