/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

val versionCatalog = extensions.getByType<VersionCatalogsExtension>().named("libs")

plugins {
    java
    jacoco
}

tasks.test {
    finalizedBy(tasks.jacocoTestReport) // report is always generated after tests run
}

tasks.jacocoTestReport {
    dependsOn(tasks.test) // tests are required to run before generating the report
}

jacoco {
    toolVersion = versionCatalog.findVersion("jacoco").get().toString()
}

tasks.jacocoTestReport {
    reports {
        csv.required.set(System.getenv("CI") != null)
        html.required.set(System.getenv("CI") == null)
        xml.required.set(System.getenv("CI") != null)
    }
}
