/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

val versionCatalog = extensions.getByType<VersionCatalogsExtension>().named("libs")

plugins {
    // Apply the java Plugin to add support for Java.
    java
    id("gradle.java.sample.java-checkstyle-conventions")
    id("gradle.java.sample.java-jacoco-conventions")
    id("gradle.java.sample.java-pmd-conventions")
    id("gradle.java.sample.java-spotbugs-conventions")
    id("gradle.java.sample.java-dependency-check-conventions")
    id("gradle.java.sample.java-sonar-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        versionCatalog.findLibrary("apache-commonsText").ifPresent() {
          implementation(it)
        }
    }
    // Test dependencies
    testImplementation(versionCatalog.findLibrary("junit-jupiter").get())
    testRuntimeOnly(versionCatalog.findLibrary("junit-jupiterPlatformLauncher").get())
}

testing {
    suites {
        // Configure the built-in test suite
        @Suppress("UNUSED_VARIABLE")
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter(versionCatalog.findVersion("junit").get().toString())
        }
    }
}
